### ISSUE TITLE
twake-node won't start

### ISSUE THREAD

**Issue by Guiraud** [linagora/Twake#1089]
**Describe the bug**
the docker twake-node exit when launching the docker compose

**To Reproduce**
```
git clone git@github.com:linagora/Twake.git
cd Twake/twake
sudo docker-compose up -d
```

Only twaketech/twake-node is not up

```
$ sudo docker logs <twaketech/twake-node container id> : 
> @twake/twake-backend@1.0.0 serve /usr/src/app
> node --max-http-header-size=30000 dist/server.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/usr/src/app/dist/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @twake/twake-backend@1.0.0 serve: `node --max-http-header-size=30000 dist/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @twake/twake-backend@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-30T18_26_44_165Z-debug.log
```

**Expected behavior**
expect twake-node to be up when docker-compose ends.

**Desktop (please complete the following information):**
 - OS: Linux debian
``` 
$uname -a
Linux <hostname> 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
```

**Comment by RomaricMourgues** [comment]
Hi, thanks for your feedback!

Did you try follow the workflow in start.sh ?

The idea is to start scylladb first, then php, then everything.
Also, you must use the distribution docker-compose.yml.dist.

```
cp -n docker-compose.yml.dist docker-compose.yml
cp -nR default-configuration/ configuration/

docker-compose pull

docker-compose up -d scylladb
sleep 5m #Wait scylladb to startup
docker-compose up -d php rabbitmq
sleep 10m #Wait php to create tables in scylladb

docker-compose up -d
```

**Comment by Guiraud** [comment]
I did it (sudo start.sh) but still : 
  NAMES
9992a4a0c102   twaketech/twake-nginx              "/bin/sh -c '/entryp…"   3 hours ago    Exited (1) 3 hours ago                                                                                              twake_nginx_1
3dcb48586d84   twaketech/twake-node               "docker-entrypoint.s…"   3 hours ago    Exited (1) 3 hours ago
