### ISSUE TITLE
System shows message that user is not a member of any workspace while he is a member

### ISSUE THREAD

**Issue by hantt12** [linagora/Twake#1798]
This issue does not always happen but it happens very frequently and when it happens user can no longer use Twake (even if you re-login or refresh the page)

Scenario 1: Update name of a workspace
Scenario 2: user delete a workspace but is still a member of another workspace

![2021-12-07_14-20.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/a8219757-34c0-4b89-8cf1-113678982a8b)

**Comment by RomaricMourgues** [comment]
Thanks, could you give me the credentials of this account and the company name ?

**Comment by RomaricMourgues** [comment]
@romanesko 

```
ode_1           | {"level":20,"time":1638865522321,"pid":23,"hostname":"a08030ec0812","name":"TwakeApp","msg":"services.database.orm.cassandra.find - Query Result (items=1): SELECT * FROM twake.workspace_counters WHERE id = 664adc60-5713-11ec-87ee-a9d56cdc4e3e AND counter_type = 'members';"}
node_1           | {"level":20,"time":1638865522324,"pid":23,"hostname":"a08030ec0812","name":"TwakeApp","msg":"CounterProvider Execute reviseCounter handler for workspace_counters"}
node_1           | {"level":50,"time":1638865522325,"pid":23,"hostname":"a08030ec0812","reqId":"req-1ca","stack":"Error: All filter parameters must be defined in entity primary key,\n          got: [\"group_id\"]\n          on table workspace_user but pk is [\"workspace_id\",\"user_id\",\"id\"],\n          instance was {}\n    at CassandraConnector.<anonymous> (/usr/src/app/dist/core/platform/services/database/services/orm/connectors/cassandra/cassandra.js:316:23)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/dist/core/platform/services/database/services/orm/connectors/cassandra/cassandra.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/src/app/dist/core/platform/services/database/services/orm/connectors/cassandra/cassandra.js:4:12)\n    at CassandraConnector.find (/usr/src/app/dist/core/platform/services/database/services/orm/connectors/cassandra/cassandra.js:308:16)\n    at Repository.<anonymous> (/usr/src/app/dist/core/platform/services/database/services/orm/repository/repository.js:54:41)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/dist/core/platform/services/database/services/orm/repository/repository.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/src/app/dist/core/platform/services/database/services/orm/repository/repository.js:4:12)\n    at Repository.find (/usr/src/app/dist/core/platform/services/database/services/orm/repository/repository.js:47:16)\n    at /usr/src/app/dist/utils/counters.js:18:45\n    at Generator.next (<anonymous>)\n    at /usr/src/app/dist/utils/counters.js:8:71\n    at new Promise (<anonymous>)","type":"Error","msg":"All filter parameters must be defined in entity primary key,\n          got: [\"group_id\"]\n          on table workspace_user but pk is [\"workspace_id\",\"user_id\",\"id\"],\n          instance was {}"}
node_1           | {"level":30,"time":1638865522326,"pid":23,"hostname":"a08030ec0812","reqId":"req-1ca","res":{"statusCode":500},"responseTime":130.46740293502808,"msg":"request completed"}
```
