### ISSUE TITLE
Unable to use Twake

### ISSUE THREAD

**Issue by asgcmo** [linagora/Twake#2449]
**Describe the bug**
It's impossible to get past login screen.

**To Reproduce**
1. Install on Ubuntu 22 LTS using official documentation.
2. Get it running.
3. Try to create an account.
4. "Create company / add members" screen appears. No option to skip it. If you press Try again you get to login screen, and your account remains locked and not usable. If you try to add company name and members you get redirected to "Create company / add members" screen again, except this time the Add button remains inactive. Only possible to get back to login screen.

**Expected behavior**
It should allow to create and use account properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/110910714/183669058-4fbd31b8-5152-495d-8a16-1a43993a5245.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 104

**Additional context**
Documentation has some issues.
- It doesn't mention that Twake will silently fail to run if 4 GB RAM requirement is not met.
- It doesn't say what to do after `docker-compose` command is completed. Figured out you have to run `sudo bash start.sh` and then `docker-compose up` to get it running.
- It says Twake will be running on port 3000 but it will be on port 8000.

**Comment by Clem-** [comment]
Hi,
Could you post the log of the containers when it fails to create the company?

It would also be very useful to tell us what version of Twake you are running.
Thanks

**Comment by asgcmo** [comment]
What commands should I run to start logging and to make sure all the relevant events are recorded?

**Comment by Clem-** [comment]
You can access the logs of your containers with
[this command](https://docs.docker.com/engine/reference/commandline/compose_logs/)  : `docker-compose logs`

**Comment by asgcmo** [comment]
The version should be latest since I'm using `git clone https://github.com/TwakeApp/Twake.git` from the documentation
```
$ docker-compose logs
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 155, in apport_excepthook
    pr.write(f)
  File "/usr/lib/python3/dist-packages/problem_report.py", line 382, in write
    file.write(v.replace(b'\n', b'\n '))
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
OSError: [Errno 28] No space left on device

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/lib/python3/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/lib/python3/dist-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
```

**Comment by Clem-** [comment]
I see you have error like `OSError: [Errno 28] No space left on device` and ` PermissionError(13, 'Permission denied')`.
Can you check you have enough free space on your device?

I also suggest to run Twake node with mongoDB as described in the [README](https://github.com/linagora/Twake/blob/main/README.md#manual-install-of-twake): `docker-compose -f docker-compose.onpremise.mongo.yml up -d`.

**Comment by asgcmo** [comment]
>Can you check you have enough free space on your device?

Okay I reinstalled the whole VM on a bigger disk. Had no idea Twake will consume the whole 7 GB that were free.

>I also suggest to run Twake node with mongoDB as described in the [README](https://github.com/linagora/Twake/blob/main/README.md#manual-install-of-twake): docker-compose -f docker-compose.onpremise.mongo.yml up -d.

```
$ sudo docker-compose -f docker-compose.onpremise.mongo.yml up -d
Starting mongo ... done
Starting twake_node_1 ... done
```
Can't open any page on any port after this.

```
~/Twake/twake$ docker-compose logs
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml, compose.yml, compose.yaml
```

My steps are:
1. Install ubuntu-22.04-live-server-amd64.
2. `sudo apt-get update`
3. `sudo apt-get upgrade`
4. `sudo apt-get install docker`
5. `sudo apt-get install docker-compose`
6. `git clone https://github.com/TwakeApp/Twake.git`
7. `cd Twake/twake`
8. Edit `docker-compose.onpremise.mongo.yml` to include `SSL_CERTS=none`
9. `sudo docker-compose -f docker-compose.onpremise.mongo.yml up -d`


Neither of the following responds:
- http://server.ip/
- http://server.ip:3000/
- http://server.ip:8000/

**Comment by asgcmo** [comment]
Not sure if this is related

```
$ sudo docker-compose -f docker-compose.onpremise.mongo.yml logs
Attaching to twake_node_1, mongo
mongo    |
mongo    | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
mongo    |   see https://jira.mongodb.org/browse/SERVER-54407
mongo    |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
mongo    |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
mongo    |
node_1   |
node_1   | > @twake/twake-backend@1.0.0 serve
node_1   | > node --unhandled-rejections=warn --max-http-header-size=30000 dist/server.js
node_1   |
node_1   | {"level":30,"time":1661250252832,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Initializing service TwakeContainer"}
node_1   | {"level":20,"time":1661250253836,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded auth"}
node_1   | {"level":20,"time":1661250253836,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded push"}
node_1   | {"level":20,"time":1661250253837,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded storage"}
node_1   | {"level":20,"time":1661250253837,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded webserver"}
node_1   | {"level":20,"time":1661250253837,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded websocket"}
node_1   | {"level":20,"time":1661250253837,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded database"}
node_1   | {"level":20,"time":1661250253837,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded cron"}
node_1   | {"level":20,"time":1661250253838,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded search"}
node_1   | {"level":20,"time":1661250253838,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded pubsub"}
node_1   | {"level":20,"time":1661250253838,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded realtime"}
node_1   | {"level":20,"time":1661250253838,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded phpnode"}
node_1   | {"level":20,"time":1661250253838,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded tracker"}
node_1   | {"level":20,"time":1661250253839,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded general"}
node_1   | {"level":20,"time":1661250253839,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded user"}
node_1   | {"level":20,"time":1661250253839,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded applicationsapi"}
node_1   | {"level":20,"time":1661250253839,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded applications"}
node_1   | {"level":20,"time":1661250253839,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded channels"}
node_1   | {"level":20,"time":1661250253840,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded notifications"}
node_1   | {"level":20,"time":1661250253840,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded messages"}
node_1   | {"level":20,"time":1661250253840,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded files"}
node_1   | {"level":20,"time":1661250253840,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded workspaces"}
node_1   | {"level":20,"time":1661250253840,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded console"}
node_1   | {"level":20,"time":1661250253841,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded previews"}
node_1   | {"level":20,"time":1661250253841,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded counter"}
node_1   | {"level":20,"time":1661250253841,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded statistics"}
node_1   | {"level":20,"time":1661250253841,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded cron"}
node_1   | {"level":20,"time":1661250253841,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded online"}
node_1   | {"level":20,"time":1661250253841,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Loaded knowledge-graph"}
node_1   | {"level":30,"time":1661250253850,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Asking for INITIALIZED on auth dependencies"}
node_1   | {"level":30,"time":1661250253850,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"webserver does not have children"}
node_1   | {"level":30,"time":1661250253850,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Initializing service webserver"}
node_1   | {"level":30,"time":1661250253871,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Service webserver is initialized"}
node_1   | {"level":30,"time":1661250253871,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Pending services: [\"TwakeContainer\"]"}
node_1   | {"level":30,"time":1661250253872,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Children of auth are all in INITIALIZED state"}
node_1   | {"level":30,"time":1661250253872,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"auth(READY) => {webserver(INITIALIZED) => {}}"}
node_1   | {"level":30,"time":1661250253872,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Initializing service auth"}
node_1   | {"level":30,"time":1661250253874,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Service auth is initialized"}
node_1   | {"level":30,"time":1661250253874,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Pending services: [\"TwakeContainer\"]"}
node_1   | {"level":30,"time":1661250253874,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Asking for INITIALIZED on push dependencies"}
node_1   | {"level":30,"time":1661250253874,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"push does not have children"}
node_1   | {"level":30,"time":1661250253875,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Initializing service push"}
node_1   | {"level":30,"time":1661250253875,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"push - Disabled"}
node_1   | {"level":30,"time":1661250253875,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Service push is initialized"}
node_1   | {"level":30,"time":1661250253875,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Pending services: [\"TwakeContainer\"]"}
node_1   | {"level":30,"time":1661250253876,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Asking for INITIALIZED on storage dependencies"}
node_1   | {"level":30,"time":1661250253876,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"storage does not have children"}
node_1   | {"level":30,"time":1661250253876,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Initializing service storage"}
node_1   | {"level":30,"time":1661250253877,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Service storage is initialized"}
node_1   | {"level":30,"time":1661250253877,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Pending services: [\"TwakeContainer\"]"}
node_1   | {"level":30,"time":1661250253877,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Asking for INITIALIZED on webserver dependencies"}
node_1   | {"level":30,"time":1661250253877,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"webserver does not have children"}
node_1   | {"level":30,"time":1661250253877,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Service webserver is already initialized"}
node_1   | {"level":30,"time":1661250253877,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Asking for INITIALIZED on websocket dependencies"}
node_1   | {"level":30,"time":1661250253878,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"webserver does not have children"}
node_1   | {"level":30,"time":1661250253878,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Service webserver is already initialized"}
node_1   | {"level":30,"time":1661250253878,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Children of websocket are all in INITIALIZED state"}
node_1   | {"level":30,"time":1661250253878,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"websocket(READY) => {webserver(INITIALIZED) => {}}"}
node_1   | {"level":30,"time":1661250253878,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Initializing service websocket"}
node_1   | {"level":30,"time":1661250253880,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Service websocket is initialized"}
node_1   | {"level":30,"time":1661250253880,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Pending services: [\"TwakeContainer\"]"}
node_1   | {"level":30,"time":1661250253880,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Asking for INITIALIZED on database dependencies"}
node_1   | {"level":30,"time":1661250253881,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"database does not have children"}
node_1   | {"level":30,"time":1661250253881,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Initializing service database"}
node_1   | {"level":30,"time":1661250253882,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Connecting to database {\"uri\":\"mongodb://mongo:27017\",\"database\":\"twake\"}"}
node_1   | {"level":50,"time":1661250283904,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Failed to connect to database"}
node_1   | {"level":50,"time":1661250283905,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Error while initializing service database"}
node_1   | {"level":50,"time":1661250283905,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","stack":"Error: Failed to connect to db\n    at Database.<anonymous> (/usr/src/app/dist/core/platform/services/database/index.js:47:23)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/dist/core/platform/services/database/index.js:12:65)","type":"Error","msg":"Failed to connect to db"}
node_1   | {"level":50,"time":1661250283906,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","msg":"Error while initializing service TwakeContainer"}
node_1   | {"level":50,"time":1661250283906,"pid":19,"hostname":"49d00f03d70c","name":"TwakeApp","stack":"Error: Failed to connect to db\n    at Database.<anonymous> (/usr/src/app/dist/core/platform/services/database/index.js:47:23)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/dist/core/platform/services/database/index.js:12:65)","type":"Error","msg":"Failed to connect to db"}
node_1   | Will exit process because of:  Error: Failed to connect to db
node_1   |     at Database.<anonymous> (/usr/src/app/dist/core/platform/services/database/index.js:47:23)
node_1   |     at Generator.throw (<anonymous>)
node_1   |     at rejected (/usr/src/app/dist/core/platform/services/database/index.js:12:65)
node_1   | npm notice
node_1   | npm notice New minor version of npm available! 8.11.0 -> 8.18.0
node_1   | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.18.0>
node_1   | npm notice Run `npm install -g npm@8.18.0` to update!
node_1   | npm notice
```

**Comment by Clem-** [comment]
Running `docker-compose logs` without `-f` flag will look for a `docker-compose` file that doesn't exist in the folder.

The latest mongo version (5.0) is not compatible with your CPU. You need to pull a previous version. 
For that, change the line 6 of `docker-compose.onpremise.mongo.yml` config with:
```
image: mongo:4.4.16
```
and run `docker-compose -f docker-compose.onpremise.mongo.yml up -d` again to pull and start the mongo container.

**Comment by asgcmo** [comment]
That solves the problem, thank you.

Though, now I see that previously I tried a different version - `docker-compose.onpremise.yml`, a build that relies on scylladb which seems to be deprecated. Logs are too long in this variant. It seems anyone who wants to get integrations is out of luck for now.

Might be a good idea to add information on CPU requirements in documentation.

**Comment by ecker00** [comment]
Side note: I came across this on Proxmox VM, and seems that changing the CPU type to `Host` solves the AVX incompatibility.
